SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
PRINT N'Altering [SalesLT].[Customer]'
GO
ALTER TABLE [SalesLT].[Customer] ADD
[BBTable] [nchar] (10) NULL,
[New Dev] [nchar] (10) NULL,
[New Dev2] [nchar] (10) NULL
GO

﻿SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
GO
SET DATEFORMAT YMD
GO
SET XACT_ABORT ON
GO

PRINT(N'Update 4 rows in [SalesLT].[Customer]')
UPDATE [SalesLT].[Customer] SET [Suffix]=N'1' WHERE [CustomerID] = 1
UPDATE [SalesLT].[Customer] SET [Suffix]=N'2' WHERE [CustomerID] = 2
UPDATE [SalesLT].[Customer] SET [Suffix]=N'3' WHERE [CustomerID] = 3
UPDATE [SalesLT].[Customer] SET [Suffix]=N'Mrs.' WHERE [CustomerID] = 4

