SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
GO
SET DATEFORMAT YMD
GO
SET XACT_ABORT ON
GO

PRINT(N'Add 8 rows to [SalesLT].[Customer]')
SET IDENTITY_INSERT [SalesLT].[Customer] ON
INSERT INTO [SalesLT].[Customer] ([CustomerID], [NameStyle], [Title], [FirstName], [MiddleName], [LastName], [Suffix], [CompanyName], [SalesPerson], [EmailAddress], [Phone], [PasswordHash], [PasswordSalt], [rowguid], [ModifiedDate], [New], [New2]) VALUES (1, 0, N'Mr.', N'Orlando', N'N.', N'Gee', N'4', N'A Bike Store', N'adventure-works\pamela0', N'orlando0@adventure-works.com', N'245-555-0173', 'L/Rlwxzp4w7RWmEgXX+/A7cXaePEPcp+KwQhl2fJL7w=', NULL, '3f5ae95e-b87d-4aed-95b4-c3797afcb74f', '2005-08-01 00:00:00.000', NULL, NULL)
INSERT INTO [SalesLT].[Customer] ([CustomerID], [NameStyle], [Title], [FirstName], [MiddleName], [LastName], [Suffix], [CompanyName], [SalesPerson], [EmailAddress], [Phone], [PasswordHash], [PasswordSalt], [rowguid], [ModifiedDate], [New], [New2]) VALUES (2, 0, N'Mr.', N'Keith', NULL, N'Harris', N'3', N'Progressive Sports', N'adventure-works\david8', N'keith0@adventure-works.com', N'170-555-0127', 'YPdtRdvqeAhj6wyxEsFdshBDNXxkCXn+CRgbvJItknw=', NULL, 'e552f657-a9af-4a7d-a645-c429d6e02491', '2006-08-01 00:00:00.000', NULL, NULL)
INSERT INTO [SalesLT].[Customer] ([CustomerID], [NameStyle], [Title], [FirstName], [MiddleName], [LastName], [Suffix], [CompanyName], [SalesPerson], [EmailAddress], [Phone], [PasswordHash], [PasswordSalt], [rowguid], [ModifiedDate], [New], [New2]) VALUES (3, 0, N'Ms.', N'Donna', N'F.', N'Carreras', N'2', N'Advanced Bike Components', N'adventure-works\jillian0', N'donna0@adventure-works.com', N'279-555-0130', 'LNoK27abGQo48gGue3EBV/UrlYSToV0/s87dCRV7uJk=', NULL, '130774b1-db21-4ef3-98c8-c104bcd6ed6d', '2005-09-01 00:00:00.000', NULL, NULL)
INSERT INTO [SalesLT].[Customer] ([CustomerID], [NameStyle], [Title], [FirstName], [MiddleName], [LastName], [Suffix], [CompanyName], [SalesPerson], [EmailAddress], [Phone], [PasswordHash], [PasswordSalt], [rowguid], [ModifiedDate], [New], [New2]) VALUES (4, 0, N'Ms.', N'Janet', N'M.', N'Gates', N'1', N'Modular Cycle Systems', N'adventure-works\jillian0', N'janet1@adventure-works.com', N'710-555-0173', 'ElzTpSNbUW1Ut+L5cWlfR7MF6nBZia8WpmGaQPjLOJA=', NULL, 'ff862851-1daa-4044-be7c-3e85583c054d', '2006-07-01 00:00:00.000', NULL, NULL)
INSERT INTO [SalesLT].[Customer] ([CustomerID], [NameStyle], [Title], [FirstName], [MiddleName], [LastName], [Suffix], [CompanyName], [SalesPerson], [EmailAddress], [Phone], [PasswordHash], [PasswordSalt], [rowguid], [ModifiedDate], [New], [New2]) VALUES (5, 0, N'Mr.', N'Lucy', NULL, N'Harrington', N'newData2', N'Metropolitan Sports Supply', N'adventure-works\shu0', N'lucy0@adventure-works.com', N'828-555-0186', 'KJqV15wsX3PG8TS5GSddp6LFFVdd3CoRftZM/tP0+R4=', NULL, '83905bdc-6f5e-4f71-b162-c98da069f38a', '2006-09-01 00:00:00.000', NULL, NULL)
INSERT INTO [SalesLT].[Customer] ([CustomerID], [NameStyle], [Title], [FirstName], [MiddleName], [LastName], [Suffix], [CompanyName], [SalesPerson], [EmailAddress], [Phone], [PasswordHash], [PasswordSalt], [rowguid], [ModifiedDate], [New], [New2]) VALUES (6, 0, N'Ms.', N'Rosmarie', N'J.', N'Carroll', N'nextData', N'Aerobic Exercise Company', N'adventure-works\linda3', N'rosmarie0@adventure-works.com', N'244-555-0112', 'OKT0scizCdIzymHHOtyJKQiC/fCILSooSZ8dQ2Y34VM=', NULL, '1a92df88-bfa2-467d-bd54-fcb9e647fdd7', '2007-09-01 00:00:00.000', NULL, NULL)
INSERT INTO [SalesLT].[Customer] ([CustomerID], [NameStyle], [Title], [FirstName], [MiddleName], [LastName], [Suffix], [CompanyName], [SalesPerson], [EmailAddress], [Phone], [PasswordHash], [PasswordSalt], [rowguid], [ModifiedDate], [New], [New2]) VALUES (7, 0, N'Mr.', N'Dominic', N'P.', N'Gash', NULL, N'Associated Bikes', N'adventure-works\shu0', N'dominic0@adventure-works.com', N'192-555-0173', 'ZccoP/jZGQm+Xpzc7RKwDhS11YFNybwcPVRYTSNcnSg=', NULL, '03e9273e-b193-448e-9823-fe0c44aeed78', '2006-07-01 00:00:00.000', NULL, NULL)
INSERT INTO [SalesLT].[Customer] ([CustomerID], [NameStyle], [Title], [FirstName], [MiddleName], [LastName], [Suffix], [CompanyName], [SalesPerson], [EmailAddress], [Phone], [PasswordHash], [PasswordSalt], [rowguid], [ModifiedDate], [New], [New2]) VALUES (10, 0, N'Ms.', N'Kathleen', N'M.', N'Garza', NULL, N'Rural Cycle Emporium', N'adventure-works\josé1', N'kathleen0@adventure-works.com', N'150-555-0127', 'Qa3aMCxNbVLGrc0b99KsbQqiVgwYDfHcsK9GZSUxcTM=', NULL, 'cdb6698d-2ff1-4fba-8f22-60ad1d11dabd', '2006-09-01 00:00:00.000', NULL, NULL)
SET IDENTITY_INSERT [SalesLT].[Customer] OFF

