SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
GO
SET DATEFORMAT YMD
GO
SET XACT_ABORT ON
GO

PRINT(N'Update 848 rows in [SalesLT].[Customer]')
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 1
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 2
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 3
UPDATE [SalesLT].[Customer] SET [Suffix]=N'1', [PasswordSalt]=NULL WHERE [CustomerID] = 4
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 5
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 6
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 7
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 10
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 11
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 12
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 16
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 18
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 19
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 20
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 21
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 22
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 23
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 24
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 25
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 28
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 34
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 37
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 38
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 39
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 40
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 41
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 42
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 43
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 46
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 47
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 48
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 52
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 55
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 56
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 57
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 58
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 59
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 60
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 61
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 64
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 65
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 66
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 70
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 73
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 74
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 75
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 76
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 77
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 78
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 79
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 82
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 83
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 84
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 88
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 91
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 92
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 93
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 94
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 95
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 96
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 97
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 100
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 101
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 102
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 106
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 109
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 110
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 111
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 112
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 113
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 114
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 115
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 118
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 119
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 120
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 124
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 127
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 128
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 129
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 130
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 131
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 132
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 133
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 136
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 137
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 138
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 142
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 145
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 146
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 147
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 148
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 149
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 150
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 151
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 154
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 155
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 156
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 160
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 163
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 164
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 165
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 166
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 167
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 168
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 169
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 172
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 173
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 174
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 178
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 180
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 181
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 182
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 183
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 184
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 185
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 186
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 187
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 190
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 191
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 192
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 196
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 197
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 198
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 199
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 200
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 201
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 202
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 203
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 204
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 205
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 208
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 209
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 210
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 214
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 217
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 218
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 219
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 220
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 221
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 222
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 223
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 226
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 227
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 228
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 232
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 235
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 236
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 237
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 238
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 239
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 240
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 241
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 244
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 245
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 246
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 250
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 253
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 254
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 255
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 256
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 257
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 258
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 259
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 262
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 263
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 264
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 268
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 271
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 272
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 273
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 274
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 275
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 276
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 277
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 280
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 281
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 282
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 286
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 287
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 288
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 289
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 290
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 291
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 292
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 293
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 294
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 295
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 298
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 299
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 300
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 304
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 306
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 307
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 308
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 309
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 310
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 311
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 312
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 313
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 316
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 317
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 318
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 322
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 323
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 325
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 326
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 327
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 328
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 329
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 330
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 331
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 334
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 335
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 336
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 340
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 343
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 344
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 345
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 346
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 347
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 348
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 349
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 352
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 353
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 354
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 358
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 360
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 361
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 362
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 363
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 364
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 365
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 366
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 367
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 370
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 371
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 372
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 376
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 377
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 379
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 380
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 381
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 382
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 383
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 384
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 385
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 388
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 389
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 390
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 394
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 395
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 397
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 398
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 399
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 400
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 401
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 402
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 403
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 406
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 407
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 408
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 412
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 415
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 416
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 417
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 418
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 419
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 420
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 421
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 424
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 425
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 426
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 430
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 431
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 433
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 434
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 435
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 436
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 437
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 438
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 439
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 442
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 443
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 444
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 448
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 451
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 452
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 453
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 454
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 455
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 456
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 457
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 460
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 461
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 462
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 466
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 468
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 469
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 470
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 471
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 472
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 473
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 474
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 475
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 478
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 479
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 480
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 484
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 487
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 488
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 489
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 490
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 491
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 492
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 493
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 496
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 497
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 498
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 502
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 504
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 505
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 506
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 507
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 508
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 509
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 510
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 511
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 514
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 515
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 516
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 520
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 523
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 526
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 527
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 528
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 529
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 532
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 533
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 534
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 538
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 541
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 542
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 543
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 544
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 545
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 546
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 547
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 550
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 551
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 552
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 556
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 559
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 560
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 561
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 562
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 563
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 564
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 565
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 568
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 569
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 570
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 574
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 577
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 578
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 579
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 580
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 581
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 582
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 583
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 586
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 587
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 588
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 592
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 595
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 596
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 597
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 598
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 599
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 600
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 601
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 604
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 605
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 606
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 607
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 608
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 609
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 610
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 613
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 617
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 620
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 621
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 622
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 623
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 624
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 625
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 626
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 629
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 630
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 631
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 635
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 637
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 641
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 643
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 644
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 645
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 646
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 647
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 648
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 649
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 650
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 653
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 654
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 655
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 659
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 660
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 661
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 665
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 668
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 669
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 670
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 671
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 672
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 673
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 674
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 677
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 678
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 679
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 683
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 685
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 689
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 692
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 693
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 694
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 695
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 696
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 697
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 698
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 701
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29485
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29486
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29489
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29490
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29492
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29494
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29496
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29497
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29499
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29502
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29503
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29505
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29506
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29508
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29510
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29511
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29515
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29517
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29521
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29522
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29523
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29524
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29525
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29527
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29528
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29530
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29531
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29532
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29533
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29535
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29536
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29539
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29541
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29544
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29545
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29546
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29548
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29550
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29553
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29554
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29557
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29558
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29559
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29560
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29562
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29565
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29566
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29567
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29568
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29569
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29570
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29571
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29573
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29574
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29576
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29577
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29579
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29580
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29582
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29583
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29584
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29585
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29587
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29588
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29590
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29591
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29593
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29596
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29598
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29599
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29600
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29601
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29603
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29605
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29606
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29608
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29611
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29612
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29614
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29615
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29616
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29617
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29618
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29620
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29622
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29623
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29625
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29627
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29629
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29631
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29632
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29635
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29636
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29637
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29638
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29639
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29641
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29643
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29644
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29645
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29646
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29649
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29650
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29651
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29653
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29654
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29655
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29659
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29660
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29662
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29663
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29666
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29668
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29671
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29673
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29674
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29677
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29680
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29682
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29683
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29684
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29686
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29688
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29689
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29690
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29692
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29695
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29696
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29698
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29699
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29702
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29703
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29705
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29708
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29709
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29710
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29711
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29713
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29714
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29716
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29717
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29719
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29720
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29722
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29727
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29728
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29730
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29732
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29733
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29734
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29736
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29737
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29738
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29739
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29740
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29741
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29742
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29743
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29744
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29747
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29748
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29750
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29753
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29755
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29757
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29758
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29761
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29763
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29764
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29765
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29766
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29768
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29769
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29770
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29771
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29772
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29773
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29774
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29775
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29776
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29778
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29780
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29781
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29782
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29783
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29784
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29785
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29787
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29788
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29789
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29792
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29793
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29794
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29796
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29797
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29799
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29800
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29803
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29805
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29806
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29807
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29809
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29810
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29813
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29815
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29816
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29818
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29819
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29822
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29824
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29826
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29827
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29830
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29831
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29832
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29834
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29835
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29840
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29842
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29843
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29847
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29848
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29850
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29851
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29852
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29853
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29854
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29855
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29857
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29858
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29859
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29860
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29861
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29862
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29863
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29864
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29865
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29866
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29867
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29868
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29870
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29871
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29872
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29873
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29874
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29876
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29877
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29879
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29881
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29883
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29884
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29885
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29889
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29890
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29891
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29892
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29893
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29895
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29897
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29898
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29900
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29901
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29902
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29903
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29904
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29905
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29906
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29907
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29908
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29910
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29911
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29913
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29914
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29915
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29918
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29919
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29920
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29921
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29922
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29924
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29925
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29926
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29928
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29929
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29930
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29931
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29932
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29934
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29935
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29936
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29937
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29938
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29939
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29941
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29942
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29943
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29944
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29946
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29948
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29949
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29950
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29952
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29953
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29954
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29955
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29956
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29957
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29959
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29962
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29964
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29967
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29969
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29971
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29973
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29974
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29975
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29978
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29980
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29981
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29982
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29983
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29985
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29987
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29988
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29990
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29991
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29992
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29994
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29997
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 29998
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30000
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30003
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30004
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30005
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30007
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30008
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30010
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30012
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30016
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30018
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30019
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30021
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30022
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30023
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30024
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30025
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30027
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30028
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30029
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30030
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30031
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30032
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30033
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30034
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30035
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30036
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30037
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30039
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30040
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30042
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30044
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30045
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30046
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30047
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30048
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30050
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30051
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30052
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30053
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30055
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30056
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30058
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30061
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30063
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30064
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30067
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30069
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30070
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30071
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30072
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30074
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30076
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30080
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30083
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30087
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30089
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30090
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30093
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30094
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30095
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30098
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30100
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30102
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30104
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30105
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30106
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30107
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30108
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30109
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30110
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30111
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30112
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30113
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30115
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30116
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30117
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30118
UPDATE [SalesLT].[Customer] SET [PasswordSalt]=NULL WHERE [CustomerID] = 30121

